http:
  port: "8081"
  
smoron:
  protocol: 'HTTPS'
  port: "443"
  host: "p-smoron-imp-jngfo9.5sc6y6-4.usa-e2.cloudhub.io"
  client_id: "![mGlmcGgybVOVdpMdO5EOjSZKlJuxkyrDGUQXCkHe5idWBVNJgM9Ydg==]"
  client_secret: "![Ewjw7z5bKweiJljnNIyTinxb2TZuGrJVsuDJ7KGTkMvkt56naw4AIA==]"
  
api:
  id: "20061175"